### ISSUE TITLE
unable to pull any of the two docker images

### ISSUE THREAD

**Issue by antonkratz** [michaelkyu/ontology#3]
I am trying to use ddot by using docker. As in subject line, I am unable to pull any of the two docker images:
```bash
kratz@kratz-VirtualBox:~ (master) $ docker pull michaelkyu/ddot-anaconda2
Using default tag: latest
Error response from daemon: manifest for michaelkyu/ddot-anaconda2:latest not found
kratz@kratz-VirtualBox:~ (master) $ docker pull michaelkyu/ddot-anaconda3
Using default tag: latest
Error response from daemon: manifest for michaelkyu/ddot-anaconda3:latest not found
```

**Comment by antonkratz** [comment]
P.S.: update Mon Nov 26 15:32:35 PST 2018:

`docker pull michaelkyu/ddot-anaconda3:v1.0rc3` *does* work, though. I believe the issue here is only that there is no "latest" tag. I suggest to either introduce such a tag, or update the documentation accordingly.

**Comment by michaelkyu** [comment]
Thanks for catching this, Anton! I erroneously thought that the "latest" tag was being constructed automatically. I've now manually tagged the docker images as "latest".

The commands

```
docker pull michaelkyu/ddot-anaconda2
docker pull michaelkyu/ddot-anaconda3
```

should work now, and they should pull the "latest" version of ddot.
